site_name: JW Player Developer Guide
theme: jwplayer
site_favicon: favicon.ico
pages:
  - Home: index.md
  - Javascript API:
    - Intro to Javascript API: api/javascript_api_introduction.md
    - Javascript API Reference: api/javascript_api_reference.md
  - Configuration:
    - Confoguration Reference: customization/configuration-reference.md
  - Customization:
    - Creating Skins: customization/css-skinning/skins_creating.md
    - Custom Icons and Fonts: customization/css-skinning/skins_fonts.md
    - CSS Reference List: customization/css-skinning/skins_reference.md
    - DOM Structure Visual Reference: customization/css-skinning/dom-structure.md
    - Example CSS File: customization/css-skinning/skins_example.md
  - Design Resources: customization/designer-kit.md
  - Beta Program:
    - HLS in HTML5: beta/html5_hls_beta.md
  - Release Notes:
    - Using Release Channels: release_notes/release_channels.md
    - JW Player 7: release_notes/release_notes_7.md
    - JW Player 6 (Legacy): release_notes/release_notes_6.md

site_dir: developer-guide
