site_name: JW Player Developer Guide
theme: jwplayer
site_favicon: favicon.ico
extra:
  product: player
pages:
  - Getting Started:
    - Introduction: index.md
    - Intro to Javascript API: api/javascript_api_introduction.md
    - Configuration Reference: customization/configuration-reference.md
    - Using Release Channels: release_notes/release_channels.md
  - Customization:
    - CSS Skinning Reference: customization/css-skinning/skins_reference.md
    - CSS Skinning Model: customization/css-skinning-model.md
    - Custom Skins: customization/css-skinning/skins_creating.md
    - Custom Icons: customization/css-skinning/custom-icons.md
    - Example CSS File: customization/css-skinning/skins_example.md
    - JW8 Designer Kit: customization/designer-kit.md
  - Advertising:
    - Ads Errors Reference: advertising/ads_errors_reference.md
  - Analytics:
    - Analytics Integrations: analytics/integrations.md
  - JW 7 Developer Guide:
        - JW7 Javascript API: jw7/javascript-api-reference.md
        - JW7 Configuration Reference: jw7/configuration-reference.md
        - JW7 CSS Skinning Reference: jw7/skins_reference.md
        - JW7 CSS Skinning Model: jw7/css-skinning-model.md
        - JW7 Custom Skins: jw7/skins_creating.md
        - JW7 Custom Icons and Fonts: jw7/skins_fonts.md
        - JW7 Example CSS File: jw7/skins_example.md
        - JW7 Designer Kit: jw7/designer-kit.md
        - JW7 Analytics Integrations: jw7/integrations.md

site_dir: developer-guide
